### ISSUE TITLE
what is the scope of this api client?

### ISSUE THREAD

**Issue by derhuerst** [pbock/fahrplan#4]
Do you want to represent the DB API as accurately as possible or rather just expose the nice things and leave out unnecessary stuff?

I was wondering if the `places` list in the response for `.station.get('…')` is useful, since other services have better geocoding & POI search apis.

**Comment by pbock** [comment]
Good point, I've been wondering about that too. My aim is to abstract away the nasty bits as much as possible, so I'll probably make `.station.find()` resolve with just an array of stations rather than the current `{ stations: […], places: […] }` object in an upcoming version. That feels a lot more consistent to me.

There could be a separate method for querying places, but seeing as there's not a lot one can do with them (until the API supports routing anyway), I might as well leave them out and wait until somebody complains.

**Comment by derhuerst** [comment]
Great, thanks!
